# Generated by Django 3.2.5 on 2021-07-10 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Voter',
        ),
    ]
